---
- hosts: all
  become: true
  tasks:
  - name: Set host variable
    set_fact:
      NEXUS_SERVER: "{{ lookup('env', 'NEXUS_SERVER') }}"
  - name: update system
    yum:
      name: '*'
      state: latest
    when: ansible_distribution == "Amazon"
  - name: install java 17
    yum:
      name: java-17-amazon-corretto-devel.x86_64
      state: present
  - name: install maven package
    yum:
      name: maven
    when: ansible_distribution == "Amazon"
  - name: install docker
    yum: 
      name: docker
      state: present
  - name: login to docker
    shell: "docker login -u admin -p iG57vVuKjpHCgPa http://{{ lookup('env', 'NEXUS_SERVER') }}:1111"
  - name: pull docker image
    shell: docker pull ec2-3-120-208-86.eu-central-1.compute.amazonaws.com:1111/repository/docker_images/petclinic:3.1.0
  - name: run the app
    shell: docker run -p 8080:8080 -d ec2-3-120-208-86.eu-central-1.compute.amazonaws.com:1111/repository/docker_images/petclinic:3.1.0